# -*- coding: utf-8 -*-
"""Yolov4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JcPAs83Z2m3qUPd6E0afEpvqNESAoz1X
"""

# loading dataset
from google.colab import drive
drive.mount('/content/drive')

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/drive/MyDrive/Yolov4/darknet-master

# Commented out IPython magic to ensure Python compatibility.
# %ls

# Commented out IPython magic to ensure Python compatibility.
# %cd darknet-master/
# %ls

!sed -i 's/OPENCV=0/OPENCV=1/' Makefile
!sed -i 's/GPU=0/GPU=1/' Makefile
!sed -i 's/CUDNN=0/CUDNN=1/' Makefile
!sed -i 's/CUDNN_HALF=0/CUDNN_HALF=1/' Makefile
!sed -i 's/LIBSO=0/LIBSO=1/' Makefile

!make -f Makefile

!chmod +777 darknet

!./darknet

# Commented out IPython magic to ensure Python compatibility.
# define helper functions
def imShow(path):
  import cv2
  import matplotlib.pyplot as plt
#   %matplotlib inline

  image = cv2.imread(path)
  height, width = image.shape[:2]
  resized_image = cv2.resize(image,(3*width, 3*height), interpolation = cv2.INTER_CUBIC)

  fig = plt.gcf()
  fig.set_size_inches(18, 10)
  plt.axis("off")
  plt.imshow(cv2.cvtColor(resized_image, cv2.COLOR_BGR2RGB))
  plt.show()

"""**yolov4.cfg**

I recommend having batch = 64 and subdivisions = 16 for ultimate results. If you run into any issues then up subdivisions to 32.

Make the rest of the changes to the cfg based on how many classes you are training your detector on.

Note: I set my max_batches = 6000, steps = 4800, 5400, I changed the classes = 1 in the three YOLO layers and filters = 18 in the three convolutional layers before the YOLO layers.

How to Configure Your Variables:

width = 416

height = 416 (these can be any multiple of 32, 416 is standard, you can sometimes improve results by making value larger like 608 but will slow down training)

max_batches = (# of classes) * 2000 (but no less than 6000 so if you are training for 1, 2, or 3 classes it will be 6000, however detector for 5 classes would have max_batches=10000)

steps = (80% of max_batches), (90% of max_batches) (so if your max_batches = 10000, then steps = 8000, 9000)

filters = (# of classes + 5) * 3 (so if you are training for one class then your filters = 18, but if you are training for 4 classes then your filters = 27)

Optional: If you run into memory issues or find the training taking a super long time. In each of the three yolo layers in the cfg, change one line from random = 1 to random = 0 to speed up training but slightly reduce accuracy of model. Will also help save memory if you run into any memory issues.
"""

# Commented out IPython magic to ensure Python compatibility.
# need to set cfg to Train Mode 
# %cd ./TEST/cfg
!sed -i 's/batch=1/batch=64/' yolov3.cfg
!sed -i 's/subdivisions=1/subdivisions=16/' yolov3.cfg
# %cd ..
# %cd ..

!wget https://github.com/AlexeyAB/darknet/releases/download/darknet_yolo_v3_optimal/yolov4.weights



#user is ideal for 30 or 90 minutes without any click , Google Collab will kickout the file.
function ClickConnect(){

console.log("Working");

document.querySelector("colab-toolbar-button#connect").click()

}

setInterval(ClickConnect,60000)

!./darknet detector train ./TEST/cfg/yolov3.data ./TEST/cfg/yolov3.cfg  -dont_show -ext_output

# show chart.png of how custom object detector did with training
imShow('chart.png')

# Commented out IPython magic to ensure Python compatibility.
# need to set cfg to Train Mode 
# %cd ./TEST/cfg
!sed -i 's/batch=64/batch=1/' yolov3.cfg
!sed -i 's/subdivisions=16/subdivisions=1/' yolov3.cfg
# %cd ..
# %cd ..

# kick off training from where it last saved
!./darknet detector valid ./TEST/cfg/yolov3.data ./TEST/cfg/yolov3.cfg  ./TEST/weights/yolov3_final.weights -dont_show -ext_output

!./darknet detector test ./TEST/cfg/yolov3.data  ./TEST/cfg/yolov3.cfg  ./TEST/weights/yolov3_final.weights ./TEST/images/P00X000-2019011000189.jpg -thresh 0.70

#!./darknet detector test cfg/coco.data cfg/yolov4.cfg yolov4.weights data/person.jpg

imShow('predictions.jpg')